{
 "title": " CliniQ - Monitoring RAG & Infrastructure",
 "tags": [
  "cliniq",
  "rag",
  "fastapi",
  "docker"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Questions posées au RAG",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rag_requests_total", "legendFormat": "Requêtes" }
   ]
  },
  {
   "title": "Erreurs Critiques RAG",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "rag_errors_total", "legendFormat": "Erreurs" }
   ]
  },
  {
   "title": "Score de Fidélité (DeepEval)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rag_faithfulness", "legendFormat": "Faithfulness" }
   ]
  },
  {
   "title": "Score de Pertinence (DeepEval)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "rag_answer_relevance", "legendFormat": "Relevance" }
   ]
  },
  {
   "title": "⏱️ Latence de l'API (Temps de réponse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "Latence moyenne (secondes)"
    }
   ]
  },
  {
   "title": " Consommation CPU des conteneurs CliniQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\"/docker.*\"}[1m])) by (id) * 100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Consommation RAM des conteneurs CliniQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=~\"/docker.*\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}